name: Pinata Upload Test (MaMeeFarm)

on:
  workflow_dispatch:  # กดรันเองได้

jobs:
  pin:
    runs-on: ubuntu-latest
    env:
      PINATA_JWT: ${{ secrets.PINATA_JWT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload test file to Pinata
        run: |
          FILE_PATH="tiktok_archive/testdata.json"
          if [ ! -f "$FILE_PATH" ]; then
            echo "File not found: $FILE_PATH"; exit 1
          fi

          echo "Uploading $FILE_PATH to Pinata..."
          RESPONSE=$(curl -s -X POST "https://api.pinata.cloud/pinning/pinFileToIPFS" \
            -H "Authorization: Bearer $PINATA_JWT" \
            -F "file=@$FILE_PATH")

          echo "$RESPONSE" > pinata_response.json
          echo "Upload done."

      - name: Commit & Push response
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "pinata-bot"
          git config user.email "bot@mameefarm.local"
          git add pinata_response.json || true
          if git diff --cached --quiet; then
            echo "No new data."; exit 0
          fi
          git commit -m "Pinata response"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
