name: TikTok → JSON Archive (metadata only)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # run every 10 minutes

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      TIKTOK_USERNAME: "mameefarm"                     # ← เปลี่ยนชื่อช่องได้ (ไม่ต้องใส่ @)
      RSS_BASE: "https://rsshub.hellogithub.workers.dev"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser python-dateutil requests

      - name: RSS → JSON (metadata only)
        run: python scripts/rss_to_json_archive.py

      - name: Commit & Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}                 # ← ใช้โทเคนที่เพิ่มใน Secrets
        run: |
          git config user.name "tiktok-archive-bot"
          git config user.email "bot@mameefarm.local"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "archive: update TikTok JSON metadata $(date)"
            git push https://x-access-token:${GH_PAT}@github.com/MaMeeFarm-Data/MaMeeFarm-TikTok-Archive.git HEAD:main
          fi
