name: TikTok oEmbed Archive (No API)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # รันทุก 12 ชม.

jobs:
  fetch-oembed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq curl

      - name: Prepare directories
        run: |
          mkdir -p tiktok
          [ -f tiktok/urls.txt ] || echo "" > tiktok/urls.txt
          mkdir -p data/tiktok/oembed data/tiktok/thumbs data/tiktok/links data/ai/manifests
          touch data/ai/manifests/index.ndjson

      - name: Normalize links (resolve vt.tiktok -> canonical)
        shell: bash
        run: |
          > data/tiktok/links/canonical.dedup.txt
          while read -r URL; do
            [ -z "$URL" ] && continue
            FINAL=$(curl -sIL -o /dev/null -w '%{url_effective}' -L "$URL" 2>/dev/null || echo "")
            [ -z "$FINAL" ] && FINAL="$URL"
            echo "$FINAL" >> data/tiktok/links/canonical.dedup.txt
          done < tiktok/urls.txt
          sort -u -o data/tiktok/links/canonical.dedup.txt data/tiktok/links/canonical.dedup.txt

      - name: Fetch oEmbed JSON + thumbnails
        shell: bash
        run: |
          N=0
          while read -r URL; do
            [ -z "$URL" ] && continue
            ID=$(echo "$URL" | sed 's#.*/video/##; s#[^0-9].*$##')
            [ -z "$ID" ] && continue
            OE="data/tiktok/oembed/${ID}.json"
            curl -s "https://www.tiktok.com/oembed?url=$URL" -o "$OE"
            TITLE=$(jq -r '.title // empty' "$OE" 2>/dev/null || true)
            THUMB=$(jq -r '.thumbnail_url // empty' "$OE" 2>/dev/null || true)
            if [ -n "$THUMB" ]; then
              curl -sL "$THUMB" -o "data/tiktok/thumbs/${ID}.jpg" || true
            fi
            # เพิ่มบรรทัดลงดัชนี AI (หากได้ oEmbed จริง)
            if [ -s "$OE" ]; then
              ESCAPED_TITLE=$(printf "%s" "$TITLE" | jq -Rs . | sed 's/^"//;s/"$//')
              echo "{\"uid\":\"tt-${ID}\",\"source_type\":\"tiktok-meta\",\"url\":\"$URL\",\"oembed\":\"$OE\",\"thumb\":\"data/tiktok/thumbs/${ID}.jpg\",\"title\":\"${ESCAPED_TITLE}\",\"split\":\"train\",\"created_at\":\"$(date -u +%FT%TZ)\"}" >> data/ai/manifests/index.ndjson
              N=$((N+1))
            fi
          done < data/tiktok/links/canonical.dedup.txt
          echo "Added/updated $N entries."

      - name: Commit changes (safe even if empty)
        shell: bash
        run: |
          git config user.name "MaMeeFarm-Bot"
          git config user.email "bot@mameefarm.com"
          git add data/tiktok/oembed/*.json || true
          git add data/tiktok/thumbs/* || true
          git add data/tiktok/links/*.txt || true
          git add data/ai/manifests/index.ndjson || true
          git diff --cached --quiet && echo "No changes to commit." || git commit -m "Archive TikTok via public oEmbed (normalize + fetch)"
          git rev-parse --verify HEAD >/dev/null 2>&1 && git push || echo "Nothing to push."
